spring:
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:mysql://192.168.199.106:3306/orion?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=round&rewriteBatchedStatements=true
    username: root
    password: 1990912
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            selelct-allow: true
        slf4j:
          enabled: true
          data-source-log-enabled: true
          connection-log-enabled: true
          connection-log-error-enabled: true
          statement-log-enabled: true
          statement-log-error-enabled: true
      web-stat-filter:
        enabled: true
        exclusions: '*.js, *.gif, *.jpg, *.png, *.css, *.ico, /druid/*'
        principal-session-name: username
        url-pattern: /api/v1/*
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: 192.168.199.101,192.168.199.102,192.168.199.103,192.168.199.104,192.168.199.105,192.168.199.106
        login-username: druid
        login-password: 1990912
        reset-enable: false
  redis:
    cluster:
      nodes:
      - 192.168.199.105:6379
      - 192.168.199.105:6380
      - 192.168.199.105:6381
      - 192.168.199.105:6382
      - 192.168.199.105:6383
      - 192.168.199.105:6384
      max-redirects: 5
    pool:
      max-active: 100
      max-wait: 30000
      max-idle: 50
      min-idle: 10
    password: null
    timeout: 60000
  data:
    mongodb:
      uri: mongodb://root:1990912@192.168.199.106:27017/orion_v1
logging:
  config: classpath:config/logback-prod.xml